// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: demo/sdk/protocolbuffer/d2.proto

package protocolbuffer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewPerson struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`  // default message rule: singular 当为字段类型默认值时，不会被序列化
	Name  []string `protobuf:"bytes,1,rep,name=name,proto3" json:"name,omitempty"`    // 切片
	Id    *int32   `protobuf:"varint,2,opt,name=id,proto3,oneof" json:"id,omitempty"` //  设置值则该字段可被序列化；不设置值则不被序列化，返回默认值
}

func (x *NewPerson) Reset() {
	*x = NewPerson{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_sdk_protocolbuffer_d2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewPerson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewPerson) ProtoMessage() {}

func (x *NewPerson) ProtoReflect() protoreflect.Message {
	mi := &file_demo_sdk_protocolbuffer_d2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewPerson.ProtoReflect.Descriptor instead.
func (*NewPerson) Descriptor() ([]byte, []int) {
	return file_demo_sdk_protocolbuffer_d2_proto_rawDescGZIP(), []int{0}
}

func (x *NewPerson) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *NewPerson) GetName() []string {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *NewPerson) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

type Outer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Outer) Reset() {
	*x = Outer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_sdk_protocolbuffer_d2_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Outer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outer) ProtoMessage() {}

func (x *Outer) ProtoReflect() protoreflect.Message {
	mi := &file_demo_sdk_protocolbuffer_d2_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outer.ProtoReflect.Descriptor instead.
func (*Outer) Descriptor() ([]byte, []int) {
	return file_demo_sdk_protocolbuffer_d2_proto_rawDescGZIP(), []int{1}
}

type SampleMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to TestOneof:
	//	*SampleMessage_Name
	//	*SampleMessage_SubMessage
	TestOneof isSampleMessage_TestOneof `protobuf_oneof:"test_oneof"`
}

func (x *SampleMessage) Reset() {
	*x = SampleMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_sdk_protocolbuffer_d2_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SampleMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampleMessage) ProtoMessage() {}

func (x *SampleMessage) ProtoReflect() protoreflect.Message {
	mi := &file_demo_sdk_protocolbuffer_d2_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampleMessage.ProtoReflect.Descriptor instead.
func (*SampleMessage) Descriptor() ([]byte, []int) {
	return file_demo_sdk_protocolbuffer_d2_proto_rawDescGZIP(), []int{2}
}

func (m *SampleMessage) GetTestOneof() isSampleMessage_TestOneof {
	if m != nil {
		return m.TestOneof
	}
	return nil
}

func (x *SampleMessage) GetName() string {
	if x, ok := x.GetTestOneof().(*SampleMessage_Name); ok {
		return x.Name
	}
	return ""
}

func (x *SampleMessage) GetSubMessage() string {
	if x, ok := x.GetTestOneof().(*SampleMessage_SubMessage); ok {
		return x.SubMessage
	}
	return ""
}

type isSampleMessage_TestOneof interface {
	isSampleMessage_TestOneof()
}

type SampleMessage_Name struct {
	Name string `protobuf:"bytes,4,opt,name=name,proto3,oneof"`
}

type SampleMessage_SubMessage struct {
	SubMessage string `protobuf:"bytes,9,opt,name=sub_message,json=subMessage,proto3,oneof"`
}

func (*SampleMessage_Name) isSampleMessage_TestOneof() {}

func (*SampleMessage_SubMessage) isSampleMessage_TestOneof() {}

type Outer_MiddleAA struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Outer_MiddleAA) Reset() {
	*x = Outer_MiddleAA{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_sdk_protocolbuffer_d2_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Outer_MiddleAA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outer_MiddleAA) ProtoMessage() {}

func (x *Outer_MiddleAA) ProtoReflect() protoreflect.Message {
	mi := &file_demo_sdk_protocolbuffer_d2_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outer_MiddleAA.ProtoReflect.Descriptor instead.
func (*Outer_MiddleAA) Descriptor() ([]byte, []int) {
	return file_demo_sdk_protocolbuffer_d2_proto_rawDescGZIP(), []int{1, 0}
}

type Outer_MiddleBB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Outer_MiddleBB) Reset() {
	*x = Outer_MiddleBB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_sdk_protocolbuffer_d2_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Outer_MiddleBB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outer_MiddleBB) ProtoMessage() {}

func (x *Outer_MiddleBB) ProtoReflect() protoreflect.Message {
	mi := &file_demo_sdk_protocolbuffer_d2_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outer_MiddleBB.ProtoReflect.Descriptor instead.
func (*Outer_MiddleBB) Descriptor() ([]byte, []int) {
	return file_demo_sdk_protocolbuffer_d2_proto_rawDescGZIP(), []int{1, 1}
}

type Outer_MiddleAA_Inner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ival  int64 `protobuf:"varint,1,opt,name=ival,proto3" json:"ival,omitempty"`
	Booly bool  `protobuf:"varint,2,opt,name=booly,proto3" json:"booly,omitempty"`
}

func (x *Outer_MiddleAA_Inner) Reset() {
	*x = Outer_MiddleAA_Inner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_sdk_protocolbuffer_d2_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Outer_MiddleAA_Inner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outer_MiddleAA_Inner) ProtoMessage() {}

func (x *Outer_MiddleAA_Inner) ProtoReflect() protoreflect.Message {
	mi := &file_demo_sdk_protocolbuffer_d2_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outer_MiddleAA_Inner.ProtoReflect.Descriptor instead.
func (*Outer_MiddleAA_Inner) Descriptor() ([]byte, []int) {
	return file_demo_sdk_protocolbuffer_d2_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *Outer_MiddleAA_Inner) GetIval() int64 {
	if x != nil {
		return x.Ival
	}
	return 0
}

func (x *Outer_MiddleAA_Inner) GetBooly() bool {
	if x != nil {
		return x.Booly
	}
	return false
}

type Outer_MiddleBB_Inner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ival  int32 `protobuf:"varint,1,opt,name=ival,proto3" json:"ival,omitempty"`
	Booly bool  `protobuf:"varint,2,opt,name=booly,proto3" json:"booly,omitempty"`
}

func (x *Outer_MiddleBB_Inner) Reset() {
	*x = Outer_MiddleBB_Inner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demo_sdk_protocolbuffer_d2_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Outer_MiddleBB_Inner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outer_MiddleBB_Inner) ProtoMessage() {}

func (x *Outer_MiddleBB_Inner) ProtoReflect() protoreflect.Message {
	mi := &file_demo_sdk_protocolbuffer_d2_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outer_MiddleBB_Inner.ProtoReflect.Descriptor instead.
func (*Outer_MiddleBB_Inner) Descriptor() ([]byte, []int) {
	return file_demo_sdk_protocolbuffer_d2_proto_rawDescGZIP(), []int{1, 1, 0}
}

func (x *Outer_MiddleBB_Inner) GetIval() int32 {
	if x != nil {
		return x.Ival
	}
	return 0
}

func (x *Outer_MiddleBB_Inner) GetBooly() bool {
	if x != nil {
		return x.Booly
	}
	return false
}

var File_demo_sdk_protocolbuffer_d2_proto protoreflect.FileDescriptor

var file_demo_sdk_protocolbuffer_d2_proto_rawDesc = []byte{
	0x0a, 0x20, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x73, 0x64, 0x6b, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x2f, 0x64, 0x32, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x22, 0x51, 0x0a, 0x09, 0x4e, 0x65,
	0x77, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x13, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52,
	0x02, 0x69, 0x64, 0x88, 0x01, 0x01, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x69, 0x64, 0x22, 0x85, 0x01,
	0x0a, 0x05, 0x4f, 0x75, 0x74, 0x65, 0x72, 0x1a, 0x3d, 0x0a, 0x08, 0x4d, 0x69, 0x64, 0x64, 0x6c,
	0x65, 0x41, 0x41, 0x1a, 0x31, 0x0a, 0x05, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x69, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x69, 0x76, 0x61, 0x6c,
	0x12, 0x14, 0x0a, 0x05, 0x62, 0x6f, 0x6f, 0x6c, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x05, 0x62, 0x6f, 0x6f, 0x6c, 0x79, 0x1a, 0x3d, 0x0a, 0x08, 0x4d, 0x69, 0x64, 0x64, 0x6c, 0x65,
	0x42, 0x42, 0x1a, 0x31, 0x0a, 0x05, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x69,
	0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x69, 0x76, 0x61, 0x6c, 0x12,
	0x14, 0x0a, 0x05, 0x62, 0x6f, 0x6f, 0x6c, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x62, 0x6f, 0x6f, 0x6c, 0x79, 0x22, 0x56, 0x0a, 0x0d, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0b,
	0x73, 0x75, 0x62, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x0a, 0x73, 0x75, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42,
	0x0c, 0x0a, 0x0a, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x42, 0x13, 0x5a,
	0x11, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x75, 0x66, 0x66,
	0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_demo_sdk_protocolbuffer_d2_proto_rawDescOnce sync.Once
	file_demo_sdk_protocolbuffer_d2_proto_rawDescData = file_demo_sdk_protocolbuffer_d2_proto_rawDesc
)

func file_demo_sdk_protocolbuffer_d2_proto_rawDescGZIP() []byte {
	file_demo_sdk_protocolbuffer_d2_proto_rawDescOnce.Do(func() {
		file_demo_sdk_protocolbuffer_d2_proto_rawDescData = protoimpl.X.CompressGZIP(file_demo_sdk_protocolbuffer_d2_proto_rawDescData)
	})
	return file_demo_sdk_protocolbuffer_d2_proto_rawDescData
}

var file_demo_sdk_protocolbuffer_d2_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_demo_sdk_protocolbuffer_d2_proto_goTypes = []interface{}{
	(*NewPerson)(nil),            // 0: person.NewPerson
	(*Outer)(nil),                // 1: person.Outer
	(*SampleMessage)(nil),        // 2: person.SampleMessage
	(*Outer_MiddleAA)(nil),       // 3: person.Outer.MiddleAA
	(*Outer_MiddleBB)(nil),       // 4: person.Outer.MiddleBB
	(*Outer_MiddleAA_Inner)(nil), // 5: person.Outer.MiddleAA.Inner
	(*Outer_MiddleBB_Inner)(nil), // 6: person.Outer.MiddleBB.Inner
}
var file_demo_sdk_protocolbuffer_d2_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_demo_sdk_protocolbuffer_d2_proto_init() }
func file_demo_sdk_protocolbuffer_d2_proto_init() {
	if File_demo_sdk_protocolbuffer_d2_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_demo_sdk_protocolbuffer_d2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewPerson); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_sdk_protocolbuffer_d2_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Outer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_sdk_protocolbuffer_d2_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SampleMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_sdk_protocolbuffer_d2_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Outer_MiddleAA); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_sdk_protocolbuffer_d2_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Outer_MiddleBB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_sdk_protocolbuffer_d2_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Outer_MiddleAA_Inner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demo_sdk_protocolbuffer_d2_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Outer_MiddleBB_Inner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_demo_sdk_protocolbuffer_d2_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_demo_sdk_protocolbuffer_d2_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*SampleMessage_Name)(nil),
		(*SampleMessage_SubMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_demo_sdk_protocolbuffer_d2_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_demo_sdk_protocolbuffer_d2_proto_goTypes,
		DependencyIndexes: file_demo_sdk_protocolbuffer_d2_proto_depIdxs,
		MessageInfos:      file_demo_sdk_protocolbuffer_d2_proto_msgTypes,
	}.Build()
	File_demo_sdk_protocolbuffer_d2_proto = out.File
	file_demo_sdk_protocolbuffer_d2_proto_rawDesc = nil
	file_demo_sdk_protocolbuffer_d2_proto_goTypes = nil
	file_demo_sdk_protocolbuffer_d2_proto_depIdxs = nil
}
